#!/usr/bin/env python3
# r32 CONDIIICLOSE: validate the three condIII-exchange residuals on GENUINE
# standard condIII hosts, generated by oper-BFS from diagSeqs (ST_PS by
# construction => automatically reduced, matching ST_PS.induct).
#  (1) JGE   : TrMax(Red N) <= Joints(Red N)!last            (>= half; equality)
#              route: j1eq(RN)=FirstNodes(RN)!last==Lng(RN)-1  AND
#                     Admpos(RN)=transJm1(RN)>0  => joints_all_TrMax
#  (2) M0RUN : adm M jm2 ==> nextR M 1 jm2 (jm2+1)  (m0-edge case)
#  (3) REGSP : Br(Red(Pred N))<>[] ==> cfbx_reg (jm2-jm3) (Red(Pred N))
# N = seg M jm3 (Lng-1); jm2 = parent(M,1,j1); jm3 = Adm(M,jm2).
import sys, time, itertools
sys.path.insert(0, '/home/koteitan/proofs/pss-proof/wt-s4b/python')
from red_model import (Lng, entry, monoT, seg, parent, Adm, adm, nadm,
                       diagSeq, le0, leR, Br, FirstNodes, Joints, Red,
                       hasParent, fmt, TrMax, Pred, nextR, nextrel1, nextrel0)

def pr(*a): print(*a, flush=True)
def is_reduced(M): return Red(list(M)) == list(M)
def s84_jm2(M): return parent(M,1,Lng(M)-1)
def s84_jm3(M): return Adm(M, s84_jm2(M))
def transJ0(M): return parent(M,0,Lng(M)-1)
def transJm1(M):  # Adm(M, parent(M,0,Lng-1))
    j0=transJ0(M)
    return None if j0 is None else Adm(M,j0)

def condIII(M):
    n=Lng(M)
    if n<3: return False
    if not hasParent(M,0,n-1): return False
    if not hasParent(M,1,n-1): return False
    j0=transJ0(M)
    return (entry(M,1,n-1)>0 and entry(M,1,j0)>=entry(M,1,n-1) and adm(M,j0))

def genuineIII(M):
    if Lng(M)-1<=1: return False
    if not monoT(M): return False
    if not hasParent(M,1,Lng(M)-1): return False
    return condIII(M)

def gen_standard(maxlen, vcap, budget):
    """BFS: start from diagSeq(0,v); apply oper(.,n). Collect hosts up to maxlen."""
    t0=time.time()
    seen=set(); frontier=[]
    for v in range(1, maxlen):
        d=diagSeq(0,v)
        if Lng(d)<=maxlen:
            frontier.append(tuple(map(tuple,d)))
    seen.update(frontier)
    hosts=list(frontier)
    while frontier:
        if time.time()-t0>budget: break
        nf=[]
        for M in frontier:
            Ml=[list(p) for p in M]
            for n in (1,2,3):
                O=oper(Ml,n) if False else None
                from red_model import oper as _op
                O=_op(Ml,n)
                if Lng(O)<1 or Lng(O)>maxlen: continue
                if any(a>vcap or b>vcap for (a,b) in O): continue
                t=tuple(map(tuple,O))
                if t not in seen:
                    seen.add(t); nf.append(t); hosts.append(t)
        frontier=nf
    return [ [list(p) for p in M] for M in hosts ]

def is_diagSeq(R):
    if len(R)==0: return False
    a=R[0][0]
    return all(x==a+k and y==a+k for k,(x,y) in enumerate(R))

def descending_br(bR):
    for J0 in range(len(bR)):
        for J1 in range(J0,len(bR)):
            a0,b0=bR[J0][0]; a1,b1=bR[J1][0]
            if not(a0>=a1 and (a0!=a1 or b0>=b1)): return False
    return True

def main():
    t0=time.time()
    maxlen=int(sys.argv[1]) if len(sys.argv)>1 else 11
    vcap  =int(sys.argv[2]) if len(sys.argv)>2 else 6
    budget=int(sys.argv[3]) if len(sys.argv)>3 else 500
    pr(f"[gen] maxlen={maxlen} vcap={vcap} budget={budget}")
    hosts=gen_standard(maxlen,vcap,budget*0.4)
    pr(f"[gen] standard hosts generated: {len(hosts)}  t={time.time()-t0:.0f}s")
    # counters
    nIII=0
    jge_ok=jge_bad=0; jge_hosts=0
    j1eqRN_ok=j1eqRN_bad=0; admposRN_ok=admposRN_bad=0
    joints_last_eq_ok=joints_last_eq_bad=0
    m0_ok=m0_bad=0; m0_hosts=0
    regsp_true=regsp_false=0; bp_empty=bp_non=0
    jge_ex=[]; j1eq_ex=[]; adm_ex=[]; m0_ex=[]; regsp_ex=[]
    for M in hosts:
        if time.time()-t0>budget: pr("[budget stop]"); break
        if not genuineIII(M): continue
        nIII+=1
        jm2=s84_jm2(M); jm3=s84_jm3(M)
        N=seg(M,jm3,Lng(M)-1); RN=Red(N)
        if jm3<jm2:
            jge_hosts+=1
            bR=Br(RN); tr=TrMax(RN)
            # route facts
            if bR:
                fnlast=FirstNodes(RN)[len(bR)-1]
                if fnlast==Lng(RN)-1: j1eqRN_ok+=1
                else:
                    j1eqRN_bad+=1
                    if len(j1eq_ex)<6: j1eq_ex.append((fmt(M),fmt(RN),fnlast,Lng(RN)-1))
                tjm1=transJm1(RN)
                if tjm1 is not None and tjm1>0: admposRN_ok+=1
                else:
                    admposRN_bad+=1
                    if len(adm_ex)<6: adm_ex.append((fmt(M),fmt(RN),tjm1))
                jl=Joints(RN)[len(bR)-1]
                if jl is not None:
                    if jl==tr: joints_last_eq_ok+=1
                    else: joints_last_eq_bad+=1
                    if tr<=jl: jge_ok+=1
                    else:
                        jge_bad+=1
                        if len(jge_ex)<6: jge_ex.append((fmt(M),fmt(RN),tr,jl))
            # REGSP
            PN=Pred(N); RPN=Red(PN); bRPN=Br(RPN); d=jm2-jm3
            if not bRPN: bp_empty+=1
            else:
                bp_non+=1
                jlp=Joints(RPN)[len(bRPN)-1]
                if jlp is not None:
                    fn=FirstNodes(RPN)[len(bRPN)-1]
                    okdiag=(entry(RPN,0,fn)==entry(RPN,1,fn))
                    desc=descending_br(bRPN)
                    cond=(d<jlp) or (d==jlp and okdiag and desc)
                    if is_reduced(RPN) and monoT(RPN) and cond: regsp_true+=1
                    else:
                        regsp_false+=1
                        if len(regsp_ex)<8: regsp_ex.append((fmt(M),fmt(RPN),d,jlp,okdiag,desc))
                else:
                    regsp_false+=1
                    if len(regsp_ex)<8: regsp_ex.append((fmt(M),fmt(RPN),d,None,None,None))
        else:
            m0_hosts+=1
            if nextrel1(M,jm2,jm2+1): m0_ok+=1
            else:
                m0_bad+=1
                if len(m0_ex)<10: m0_ex.append((fmt(M),jm2,adm(M,jm2)))
    pr("="*66)
    pr(f"genuine condIII standard hosts = {nIII} (guard {jge_hosts}, m0-edge {m0_hosts})")
    pr(f"[1 JGE] TrMax<=Joints!last  ok={jge_ok} bad={jge_bad}")
    pr(f"        j1eq(RN) ok={j1eqRN_ok} bad={j1eqRN_bad}")
    pr(f"        Admpos(RN)=transJm1(RN)>0 ok={admposRN_ok} bad={admposRN_bad}")
    pr(f"        Joints(RN)!last==TrMax(RN) ok={joints_last_eq_ok} bad={joints_last_eq_bad}")
    for e in jge_ex: pr("   JGE BAD:",e)
    for e in j1eq_ex: pr("   J1EQ BAD:",e)
    for e in adm_ex: pr("   ADMPOS BAD:",e)
    pr(f"[2 M0RUN] adm-jm2 => nextR1 jm2 (jm2+1) ok={m0_ok} bad={m0_bad}")
    for e in m0_ex: pr("   M0 BAD:",e)
    pr(f"[3 REGSP] Br(Red(Pred N)): empty={bp_empty} nonempty={bp_non}")
    pr(f"        cfbx_reg(Red(Pred N)) [Br<>[] only] TRUE={regsp_true} FALSE={regsp_false}")
    for e in regsp_ex: pr("   REGSP FALSE:",e)
    pr(f"t={time.time()-t0:.0f}s")

if __name__=='__main__':
    main()
