#!/usr/bin/env python3
"""Empirical audit of the gtw_tile residual (and GTWF as an ST_PS inductive
invariant) on a BROAD ST_PS closure, generated by BFS from diagSeq seeds under
oper(.,n).  Per the empirical-first / no-small-sampling rule, we push depth and
size well past the small closure that produced false positives before.

  GTWF(M) := for every y with a row-1 parent, the open interval
             (parent M 1 y, y) consists of nodes that ALSO have a row-1 parent
             landing >= parent M 1 y.

  gtw_tile (the inductive STEP, tiling branch):
     GTWF(M) & 1<Lng M & endpoint!=(0,0) & hasParent(M,idx1,j1)
        ==>  GTWF(oper(M,n))   for all n>=1.
"""
import sys
from red_model import (Lng, entry, oper, parent, hasParent, idx1, diagSeq, fmt)

def GTWF(M):
    n = Lng(M)
    for y in range(n):
        if hasParent(M, 1, y):
            py = parent(M, 1, y)
            for z in range(py + 1, y):
                if not (hasParent(M, 1, z) and parent(M, 1, z) >= py):
                    return False
    return True

def tiling_branch(M):
    j1 = Lng(M) - 1
    if j1 == 0:
        return False
    if entry(M, 0, j1) == 0 and entry(M, 1, j1) == 0:
        return False
    return hasParent(M, idx1(M, j1), j1)

def build_closure(seeds, ns, maxlen, maxe):
    seen = set()
    frontier = []
    def key(M): return tuple(M)
    def maxent(M): return max((max(a, b) for (a, b) in M), default=0)
    for s in seeds:
        k = key(s)
        if k not in seen and Lng(s) <= maxlen and maxent(s) <= maxe:
            seen.add(k); frontier.append(s)
    closure = list(frontier)
    while frontier:
        nxt = []
        for M in frontier:
            for n in ns:
                N = oper(M, n)
                k = key(N)
                if k not in seen and Lng(N) <= maxlen and maxent(N) <= maxe:
                    seen.add(k); nxt.append(N); closure.append(N)
        frontier = nxt
    return closure

def main():
    maxlen = int(sys.argv[1]) if len(sys.argv) > 1 else 18
    maxe   = int(sys.argv[2]) if len(sys.argv) > 2 else 6
    nmax   = int(sys.argv[3]) if len(sys.argv) > 3 else 5
    seeds = [diagSeq(a, b) for a in range(0, 3) for b in range(a, a + 5)]
    ns = list(range(1, nmax + 1))
    closure = build_closure(seeds, ns, maxlen, maxe)
    print(f"closure size (maxlen={maxlen}, maxe={maxe}, n=1..{nmax}): {len(closure)}")

    # 1) GTWF holds on the whole closure?
    inv_fail = [M for M in closure if not GTWF(M)]
    print(f"GTWF invariant: tested={len(closure)} FAIL={len(inv_fail)}"
          + (f"  ex={fmt(inv_fail[0])}" if inv_fail else "  OK"))

    # 2) gtw_tile step: GTWF(M) & tiling ==> GTWF(oper(M,n)) for all n
    step_t = step_f = 0
    ex = None
    for M in closure:
        if GTWF(M) and tiling_branch(M):
            for n in ns:
                N = oper(M, n)
                step_t += 1
                if not GTWF(N):
                    step_f += 1
                    if ex is None: ex = (fmt(M), n, fmt(N))
    print(f"gtw_tile step:  tested={step_t} FAIL={step_f}"
          + (f"  ex M={ex[0]} n={ex[1]} -> N={ex[2]}" if ex else "  OK"))

if __name__ == "__main__":
    main()
