import «6».«6.1-le-IncrFirst-invariance»
import «6».«6.2-multi-criterion»
import «6».«6.2-mono-ancestor-slice»
import «6».«6.2-mono-prefix»
import «6».«6.2-P-IncrFirst-equivariance»
import «6».«6.2-P-components-nonmulti»
import «6».«6.2-P-additivity»
import «6».«6.2-P-fseq»
import «6».«6.2-nonmulti-fseq»
import «6».«6.3-adm-slice»
import «6».«6.3-admof-slice»
import «6».«6.3-marked-slice»
