import «6».«6.1-le-IncrFirst-invariance»
import «6».«6.2-multi-criterion»
import «6».«6.2-mono-ancestor-slice»
import «6».«6.2-mono-prefix»
import «6».«6.2-P-IncrFirst-equivariance»
import «6».«6.2-P-components-nonmulti»
import «6».«6.2-P-additivity»
import «6».«6.2-P-fseq»
import «6».«6.2-nonmulti-fseq»
import «6».«6.3-adm-slice»
import «6».«6.3-admof-slice»
import «6».«6.3-marked-slice»
import «6».«6.4-P-IdxSum»
import «6».«6.4-P-IdxSum-characterization»
import «6».«6.4-P-leftend-mono»
import «6».«6.4-mono-slice-next»
import «6».«6.4-FirstNodes-TrMax-Joints»
import «6».«6.4-FirstNodes-Joints-mono»
import «6».«6.4-mono-slice»
import «6».«6.5-Red-welldefined»
import «6».«6.5-Red-IncrFirst-invariance»
import «6».«6.5-Red-idempotence»
import «6».«6.5-Lng-Red-invariance»
import «6».«6.5-Red-preserves-zeroT»
import «6».«6.5-Red-preserves-monoT»
import «6».«6.5-monoT-Red»
