#!/usr/bin/env python3
"""Generate a line-anchored table of contents for the big .thy files.

Scans for structure markers:
  - banner comments   (* ===== ... ===== *)
  - section/subsection headings
and emits docs/thy-toc.md with one `line<TAB>text` row per marker, grouped by
file. Regenerate after every C->B fold (or any bulk edit of a frozen layer):

    python3 tools/make_toc.py

Agents: grep docs/thy-toc.md first to locate a topic/round/prefix, then Read
the .thy at the reported line. Grep by lemma NAME still goes straight to the
.thy — the TOC is for topic-level orientation only.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FILES = [
    'pss_defs.thy',
    'pss_paper.thy',
    'pss_mechanized.thy',
    'layerB/pss_wip.thy',
    'layerC/pss_scratch.thy',
]
OUT = ROOT / 'docs' / 'thy-toc.md'

BANNER = re.compile(r'^\(\*\s*=+\s*(.*?)\s*=*\s*\*\)\s*$')
SECTION = re.compile(r'^(section|subsection|subsubsection)\s*\\<open>(.*)\\<close>')
SECTION_Q = re.compile(r'^(section|subsection|subsubsection)\s*"(.*?)"')

def rows(path: Path):
    for i, line in enumerate(path.read_text(errors='replace').splitlines(), 1):
        m = BANNER.match(line)
        if m:
            txt = m.group(1).strip()
            if txt and not re.fullmatch(r'=+', txt):
                yield i, 'banner', txt
            continue
        m = SECTION.match(line) or SECTION_Q.match(line)
        if m:
            yield i, m.group(1), m.group(2).strip()

def main():
    out = ['# thy-toc — line-anchored contents of the theory files',
           '',
           'GENERATED by `python3 tools/make_toc.py` — do not edit by hand.',
           'Format: `line<TAB>kind<TAB>text`. Regenerate after every C->B fold.',
           '']
    for rel in FILES:
        p = ROOT / rel
        if not p.exists():
            continue
        out.append(f'## {rel}')
        out.append('')
        for i, kind, txt in rows(p):
            out.append(f'{i}\t{kind}\t{txt}')
        out.append('')
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print(f'wrote {OUT} ({len(out)} lines)')

if __name__ == '__main__':
    main()
